package com.index.table.service;

import java.util.Collections;
import java.util.Vector;

import com.index.table.to.Book;

public class UserService {

    public static Vector<Book> getUserList() {
        Vector<Book> bookList = new Vector<Book>();

        Book book = new Book("Things Fall Apart ", "Chinua Achebe ", "1958", " Nigeria ", "English");
        bookList.add(book);
        book = new Book("Fairy tales ", "Hans Christian Andersen ", "1835837 ", "Denmark ", "Danish");
        bookList.add(book);
        book = new Book("The Divine Comedy ", "Dante Alighieri ", "126581321 ", "Florence ", "Italian");
        bookList.add(book);
        book = new Book("Epic of Gilgamesh ", "Anonymous ", "18th 8 17th century BC ", "Sumer and Akkadian Empire ", "Akkadian");
        bookList.add(book);
        book = new Book("Book of Job ", "Anonymous ", "6th 8 4th century BC ", "Achaemenid Empire ", "Hebrew");
        bookList.add(book);
        book = new Book("One Thousand and One Nights ", "Anonymous ", "70081500 ", "India/Iran/Iraq/Egypt ", "Arabic");
        bookList.add(book);
        book = new Book("Nj8l's Saga ", "Anonymous ", "13th century ", "Iceland ", "Old Norse");
        bookList.add(book);
        book = new Book("Pride and Prejudice ", "Jane Austen ", "1813", " United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Le P8re Goriot ", "Honor8 de Balzac ", "1835", " France ", "French");
        bookList.add(book);
        book = new Book("Molloy, Malone Dies, The Unnamable, a trilogy ", "Samuel Beckett ", "1951853 ", "Republic of Ireland ", "French, English");
        bookList.add(book);
        book = new Book("The Decameron ", "Giovanni Boccaccio ", "1349853 ", "Ravenna ", "Italian");
        bookList.add(book);
        book = new Book("Ficciones ", "Jorge Luis Borges ", "1944886 ", "Argentina ", "Spanish");
        bookList.add(book);
        book = new Book("Wuthering Heights ", "Emily Bront8 ", "1847", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("The Stranger ", "Albert Camus ", "1942", "   Algeria, French Empire ", "French");
        bookList.add(book);
        book = new Book("Poems ", "Paul Celan ", "1952", "    Romania, France ", "German");
        bookList.add(book);
        book = new Book("Journey to the End of the Night ", "Louis-Ferdinand C8line ", "1932", "  France ", "French");
        bookList.add(book);
        book = new Book("Don Quixote ", "Miguel de Cervantes ", "1605 (part 1), 1615 (part 2) ", "Spain ", "Spanish");
        bookList.add(book);
        book = new Book("The Canterbury Tales ", "Geoffrey Chaucer ", "14th century ", "England ", "English");
        bookList.add(book);
        book = new Book("Stories ", "Anton Chekhov ", "1886", "   Russia ", "Russian");
        bookList.add(book);
        book = new Book("Nostromo ", "Joseph Conrad ", "1904", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Great Expectations ", "Charles Dickens ", "1861", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Jacques the Fatalist ", "Denis Diderot ", "1796", "  France ", "French");
        bookList.add(book);
        book = new Book("Berlin Alexanderplatz ", "Alfred D8blin ", "1929", " Germany ", "German");
        bookList.add(book);
        book = new Book("Crime and Punishment ", "Fyodor Dostoyevsky ", "1866", " Russia ", "Russian");
        bookList.add(book);
        book = new Book("The Idiot ", "Fyodor Dostoyevsky ", "1869", "    Russia ", "Russian");
        bookList.add(book);
        book = new Book("The Possessed ", "Fyodor Dostoyevsky ", "1872", "    Russia ", "Russian");
        bookList.add(book);
        book = new Book("The Brothers Karamazov ", "Fyodor Dostoyevsky ", "1880", "   Russia ", "Russian");
        bookList.add(book);
        book = new Book("Middlemarch ", "George Eliot ", "1871", "    United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Invisible Man ", "Ralph Ellison ", "1952", " United States ", "English");
        bookList.add(book);
        book = new Book("Medea ", "Euripides ", "431 BC ", "Athens ", "Classical Greek");
        bookList.add(book);
        book = new Book("Absalom, Absalom! ", "William Faulkner ", "1936", "  United States ", "English");
        bookList.add(book);
        book = new Book("The Sound and the Fury ", "William Faulkner ", "1929", " United States ", "English");
        bookList.add(book);
        book = new Book("Madame Bovary ", "Gustave Flaubert ", "1857", "  France ", "French");
        bookList.add(book);
        book = new Book("Sentimental Education ", "Gustave Flaubert ", "1869", "  France ", "French");
        bookList.add(book);
        book = new Book("Gypsy Ballads ", "Federico Garc8a Lorca ", "1928", " Spain ", "Spanish");
        bookList.add(book);
        book = new Book("One Hundred Years of Solitude ", "Gabriel Garc8a M8rquez ", "1967", "    Colombia ", "Spanish");
        bookList.add(book);
        book = new Book("Love in the Time of Cholera ", "Gabriel Garc8a M8rquez ", "1985", "  Colombia ", "Spanish");
        bookList.add(book);
        book = new Book("Faust ", "Johann Wolfgang von Goethe ", "1832", "    Saxe-Weimar, Germany ", "German");
        bookList.add(book);
        book = new Book("Dead Souls ", "Nikolai Gogol ", "1842", "    Russia ", "Russian");
        bookList.add(book);
        book = new Book("The Tin Drum ", "G8nter Grass ", "1959", "   West Germany ", "German");
        bookList.add(book);
        book = new Book("The Devil to Pay in the Backlands ", "Jo8o Guimar8es Rosa ", "1956", "   Brazil ", "Portuguese");
        bookList.add(book);
        book = new Book("Hunger ", "Knut Hamsun ", "1890", "  Norway ", "Norwegian");
        bookList.add(book);
        book = new Book("The Old Man and the Sea ", "Ernest Hemingway ", "1952", "    United States ", "English");
        bookList.add(book);
        book = new Book("Iliad ", "Homer ", "8508750 BC ", "Possibly Smyrna ", "Classical Greek");
        bookList.add(book);
        book = new Book("Odyssey ", "Homer ", "8th century BC ", "Possibly Smyrna ", "Classical Greek");
        bookList.add(book);
        book = new Book("A Doll's House ", "Henrik Ibsen ", "1879", " Norway ", "Norwegian");
        bookList.add(book);
        book = new Book("Ulysses ", "James Joyce ", "1922", " Irish Free State ", "English");
        bookList.add(book);
        book = new Book("Stories ", "Franz Kafka ", "1924", " Austria ", "German");
        bookList.add(book);
        book = new Book("The Trial ", "Franz Kafka ", "1925", "   Austria ", "German");
        bookList.add(book);
        book = new Book("The Castle ", "Franz Kafka ", "1926", "  Austria ", "German");
        bookList.add(book);
        book = new Book("Shakuntala ", "Kalidasa ", "1st century BC 8 4th century AD ", "India ", "Sanskrit");
        bookList.add(book);
        book = new Book("The Sound of the Mountain ", "Yasunari Kawabata ", "1954", " Japan ", "Japanese");
        bookList.add(book);
        book = new Book("Zorba the Greek ", "Nikos Kazantzakis ", "1946", "   Greece ", "Greek");
        bookList.add(book);
        book = new Book("Sons and Lovers ", "D. H. Lawrence ", "1913", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Independent People ", "Halld8r Laxness ", "1934835 ", "Iceland ", "Icelandic");
        bookList.add(book);
        book = new Book("Poems ", "Giacomo Leopardi ", "1818", "  Italy ", "Italian");
        bookList.add(book);
        book = new Book("The Golden Notebook ", "Doris Lessing ", "1962", "   United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Pippi Longstocking ", "Astrid Lindgren ", "1945", "  Sweden ", "Swedish");
        bookList.add(book);
        book = new Book("A Madman's Diary ", "Lu Xun ", "1918", " China ", "Chinese");
        bookList.add(book);
        book = new Book("Children of Gebelawi ", "Naguib Mahfouz ", "1959", " Egypt ", "Arabic");
        bookList.add(book);
        book = new Book("Buddenbrooks ", "Thomas Mann ", "1901", "    Germany ", "German");
        bookList.add(book);
        book = new Book("The Magic Mountain ", "Thomas Mann ", "1924", "  Germany ", "German");
        bookList.add(book);
        book = new Book("Moby-Dick ", "Herman Melville ", "1851", "   United States ", "English");
        bookList.add(book);
        book = new Book("Essays ", "Michel de Montaigne ", "1595", "  France ", "French");
        bookList.add(book);
        book = new Book("History ", "Elsa Morante ", "1974", "    Italy ", "Italian");
        bookList.add(book);
        book = new Book("Beloved ", "Toni Morrison ", "1987", "   United States ", "English");
        bookList.add(book);
        book = new Book("The Tale of Genji ", "Murasaki Shikibu ", "11th century ", "Japan ", "Japanese");
        bookList.add(book);
        book = new Book("The Man Without Qualities ", "Robert Musil ", "1930832 ", "Austria ", "German");
        bookList.add(book);
        book = new Book("Lolita ", "Vladimir Nabokov ", "1955", " Russia/United States ", "English");
        bookList.add(book);
        book = new Book("Nineteen Eighty-Four ", "George Orwell ", "1949", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Metamorphoses ", "Ovid ", "1st century AD ", "Roman Empire ", "Classical Latin");
        bookList.add(book);
        book = new Book("The Book of Disquiet ", "Fernando Pessoa ", "1928", "    Portugal ", "Portuguese");
        bookList.add(book);
        book = new Book("Tales ", "Edgar Allan Poe ", "19th century ", "United States ", "English");
        bookList.add(book);
        book = new Book("In Search of Lost Time ", "Marcel Proust ", "1913827 ", "France ", "French");
        bookList.add(book);
        book = new Book("The Life of Gargantua and of Pantagruel ", "Fran8ois Rabelais ", "1532834 ", "France ", "French");
        bookList.add(book);
        book = new Book("Pedro P8ramo ", "Juan Rulfo ", "1955", " Mexico ", "Spanish");
        bookList.add(book);
        book = new Book("Masnavi ", "Rumi ", "1258873 ", "Persia, Mongol Empire ", "Persian");
        bookList.add(book);
        book = new Book("Midnight's Children ", "Salman Rushdie ", "1981", "  United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Bostan ", "Saadi ", "1257", "    Persia, Mongol Empire ", "Persian");
        bookList.add(book);
        book = new Book("Season of Migration to the North ", "Tayeb Salih ", "1971", "    Sudan ", "Arabic");
        bookList.add(book);
        book = new Book("Blindness ", "Jos8 Saramago ", "1995", " Portugal ", "Portuguese");
        bookList.add(book);
        book = new Book("Hamlet ", "William Shakespeare ", "1603", "  England ", "English");
        bookList.add(book);
        book = new Book("King Lear ", "William Shakespeare ", "1608", "   England ", "English");
        bookList.add(book);
        book = new Book("Othello ", "William Shakespeare ", "1609", " England ", "English");
        bookList.add(book);
        book = new Book("Oedipus the King ", "Sophocles ", "430 BC ", "Athens ", "Classical Greek");
        bookList.add(book);
        book = new Book("The Red and the Black ", "Stendhal ", "1830", "  France ", "French");
        bookList.add(book);
        book = new Book("Tristram Shandy ", "Laurence Sterne ", "1760", " England ", "English");
        bookList.add(book);
        book = new Book("Confessions of Zeno ", "Italo Svevo ", "1923", " Italy ", "Italian");
        bookList.add(book);
        book = new Book("Gulliver's Travels ", "Jonathan Swift ", "1726", "   Ireland ", "English");
        bookList.add(book);
        book = new Book("War and Peace ", "Leo Tolstoy ", "186581869 ", "Russia ", "Russian");
        bookList.add(book);
        book = new Book("Anna Karenina ", "Leo Tolstoy ", "1877", "   Russia ", "Russian");
        bookList.add(book);
        book = new Book("The Death of Ivan Ilyich ", "Leo Tolstoy ", "1886", "    Russia ", "Russian");
        bookList.add(book);
        book = new Book("Adventures of Huckleberry Finn ", "Mark Twain ", "1884", "   United States ", "English");
        bookList.add(book);
        book = new Book("Ramayana ", "Valmiki ", "3rd century BC 8 3rd century AD ", "India ", "Sanskrit");
        bookList.add(book);
        book = new Book("Aeneid ", "Virgil ", "29819 BC ", "Roman Empire ", "Classical Latin");
        bookList.add(book);
        book = new Book("Mahabharata ", "Vyasa ", "4th century BC 8 4th century AD ", "India ", "Sanskrit");
        bookList.add(book);
        book = new Book("Leaves of Grass ", "Walt Whitman ", "1855", "    United States ", "English");
        bookList.add(book);
        book = new Book("Mrs Dalloway ", "Virginia Woolf ", "1925", " United Kingdom ", "English");
        bookList.add(book);
        book = new Book("To the Lighthouse ", "Virginia Woolf ", "1927", "    United Kingdom ", "English");
        bookList.add(book);
        book = new Book("Memoirs of Hadrian ", "Marguerite Yourcenar ", "1951", " France ", "French");
        bookList.add(book);
        Collections.sort(bookList);
        return bookList;
    }

}
